//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class despensometroEntities : DbContext
    {
        public despensometroEntities()
            : base("name=despensometroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<estoque> estoque { get; set; }
        public DbSet<fabricante> fabricante { get; set; }
        public DbSet<ingrediente> ingrediente { get; set; }
        public DbSet<listaCompras> listaCompras { get; set; }
        public DbSet<listaCompras_produto> listaCompras_produto { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<produto_estoque> produto_estoque { get; set; }
        public DbSet<receitaInternet> receitaInternet { get; set; }
        public DbSet<receitaUsuario> receitaUsuario { get; set; }
        public DbSet<tipo> tipo { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
