//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque
    {
        public estoque()
        {
            this.produto_estoque = new HashSet<produto_estoque>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int estoque_id { get; set; }
        public string estoque_nome { get; set; }
        public bool compartilhavel { get; set; }
    
        public virtual ICollection<produto_estoque> produto_estoque { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
