//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingrediente
    {
        public ingrediente()
        {
            this.receitaUsuario = new HashSet<receitaUsuario>();
        }
    
        public int ingrediente_id { get; set; }
        public Nullable<int> produto_id { get; set; }
        public string ingrediente_nome { get; set; }
        public string quantidade_ingrediente { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual ICollection<receitaUsuario> receitaUsuario { get; set; }
    }
}
