//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listaCompras
    {
        public listaCompras()
        {
            this.listaCompras_produto = new HashSet<listaCompras_produto>();
        }
    
        public int lista_id { get; set; }
        public string nome_lista { get; set; }
        public bool compartilhavel { get; set; }
        public int usuario_id { get; set; }
    
        public virtual ICollection<listaCompras_produto> listaCompras_produto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
