//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receitaInternet
    {
        public receitaInternet()
        {
            this.produto = new HashSet<produto>();
        }
    
        public int receita_id { get; set; }
        public string nome_receita { get; set; }
        public string link_receita { get; set; }
    
        public virtual ICollection<produto> produto { get; set; }
    }
}
