//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receitaUsuario
    {
        public int receita_id { get; set; }
        public string nome_receita { get; set; }
        public Nullable<int> ingrediente_id { get; set; }
        public string modo_preparo { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual ingrediente ingrediente { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
