//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.listaCompras = new HashSet<listaCompras>();
            this.receitaUsuario = new HashSet<receitaUsuario>();
            this.estoque = new HashSet<estoque>();
        }
    
        public int usuario_id { get; set; }
        public string nome_usuario { get; set; }
        public string login_usuario { get; set; }
        public string senha { get; set; }
    
        public virtual ICollection<listaCompras> listaCompras { get; set; }
        public virtual ICollection<receitaUsuario> receitaUsuario { get; set; }
        public virtual ICollection<estoque> estoque { get; set; }
    }
}
